name: devbio-napari-env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - aiofiles=22.1.0
  - aiosqlite=0.20.0
  - alabaster=0.7.16
  - annotated-types=0.7.0
  - anyio=3.7.1
  - aom=3.9.1
  - apoc-backend=0.12.0
  - app-model=0.3.0
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - attrs=25.3.0
  - autopep8=2.3.2
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-blosc2=2.17.1
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachey=0.2.1
  - certifi=2025.4.26
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.9.23
  - cycler=0.12.1
  - cython=0.29.37
  - cytoolz=1.0.1
  - czifile=2019.7.2.1
  - dask-core=2024.8.0
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - devbio-napari=0.11.0
  - docstring_parser=0.16
  - docutils=0.21.2
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fasteners=0.19
  - ffmpeg=4.3.1
  - fftw=3.3.10
  - flexcache=0.3
  - flexparser=0.4
  - fonttools=4.58.2
  - fqdn=1.5.1
  - freetype=2.13.3
  - freetype-py=2.5.1
  - fsspec=2025.5.1
  - funcsigs=1.0.2
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.2.0
  - hdbscan=0.8.39
  - hdf5=1.14.6
  - heapdict=1.0.1
  - hpack=4.1.0
  - hsluv=5.0.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - in-n-out=0.2.1
  - iniconfig=2.0.0
  - intel-openmp=2025.1.0
  - ipycanvas=0.13.3
  - ipyevents=2.0.2
  - ipykernel=6.29.5
  - ipympl=0.9.7
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=1.24.0
  - jupyter_server_fileid=0.9.2
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jupytext=1.17.2
  - jxrlib=1.1
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.6
  - libcurl=8.14.1
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libhwy=1.2.0
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libitk=5.4.4
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.10.4
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - loguru=0.7.3
  - lz4-c=1.10.0
  - magicgui=0.10.1
  - mako=1.3.10
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.1.3
  - mkl=2020.4
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - napari=0.5.6
  - napari-3d-ortho-viewer=0.1.5
  - napari-accelerated-pixel-and-object-classification=0.14.1
  - napari-animation=0.0.8
  - napari-assistant=0.6.0
  - napari-base=0.5.6
  - napari-blob-detection=0.0.2
  - napari-brightness-contrast=0.1.8
  - napari-clusters-plotter=0.8.1
  - napari-console=0.1.3
  - napari-crop=0.1.9
  - napari-curtain=0.1.1
  - napari-czifile2=0.2.7
  - napari-folder-browser=0.1.3
  - napari-layer-details-display=0.1.5
  - napari-mouse-controls=0.1.3
  - napari-plot-profile=0.2.2
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.4
  - napari-plugin-search=0.1.3
  - napari-pyclesperanto-assistant=0.22.1
  - napari-pystackreg=0.1.4
  - napari-roi=0.1.8
  - napari-segment-blobs-and-things-with-membranes=0.3.11
  - napari-simpleitk-image-processing=0.4.9
  - napari-skimage-regionprops=0.10.1
  - napari-svg=0.2.1
  - napari-tabu=0.1.5
  - napari-time-slicer=0.5.0
  - napari-tools-menu=0.1.20
  - napari-workflow-inspector=0.2.2
  - napari-workflow-optimizer=0.1.4
  - napari-workflows=0.2.10
  - nbclassic=1.3.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - npe2=0.7.8
  - numba=0.60.0
  - numcodecs=0.12.1
  - numpy=1.23.5
  - numpydoc=1.8.0
  - opencl-headers=2024.10.24
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pint=0.24.4
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - platymatch=0.0.3
  - pluggy=1.6.0
  - ply=3.11
  - pooch=1.8.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - psygnal=0.13.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyclesperanto-prototype=0.24.4
  - pycodestyle=2.13.0
  - pyconify=0.2.1
  - pycparser=2.22
  - pydantic=2.11.5
  - pydantic-compat=0.1.2
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyopencl=2025.1
  - pyopengl=3.1.9
  - pyparsing=3.2.3
  - pyperclip=1.9.0
  - pyproject_hooks=1.2.0
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtgraph=0.13.7
  - pysocks=1.7.1
  - pystackreg=0.2.8
  - pytest=8.4.0
  - python=3.9.23
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytools=2024.1.14
  - pytz=2025.2
  - pywavelets=1.6.0
  - pywin32=307
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - rav1e=0.7.1
  - redlionfish=0.10
  - referencing=0.36.2
  - reikna=0.8.0
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rpds-py=0.25.1
  - scikit-image=0.24.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simpleitk=2.5.0
  - sip=6.10.0
  - siphash24=1.7
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.7
  - sphinx=7.4.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.3
  - stackview=0.18.0
  - statsmodels=0.14.4
  - superqt=0.7.3
  - svt-av1=3.0.2
  - tabulate=0.9.0
  - tbb=2022.0.0
  - terminado=0.18.1
  - the-segmentation-game=0.2.0
  - threadpoolctl=3.6.0
  - tifffile=2024.6.18
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomli-w=1.2.0
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transforms3d=0.4.2
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vispy=0.14.3
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win32_setctime=1.2.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wordcloud=1.9.4
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zarr=2.18.2
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
